PROBLEM 1

In [6]:
from sklearn.model_selection import train_test_split

In [25]:
import numpy as np

def scratch_train_test_split(x,y, train_size=0.8, seed=0):
    """
        x : The following forms of ndarray, shape (n_samples, n_features)
        Training data
        
    y : The following forms of ndarray, shape (n_samples,)
        correct answer value
    train_size : float (0<train_size<1)
        specify what percentage to use as a train
    Returns
    x_train : The following forms of ndarray, shape (n_samples, n_features)
        Training data
    x_test : The following forms of ndarray, shape(n_saples, n_features)
        validation data
    y_train : The following forms of ndarray, shape (n_samples,)
        correct data value of training data
    y_test : The following forms of ndarray, shape (n_samples,)
        correct value of verification data
    """

        
        
    np.random.seed(seed)
    np.random.shuffle(x)
    
    np.random.seed(seed)
    np.random.shuffle(y)
    
    elements_x = len(x)
    elements_y = len(y)
    
    x_split = int(elements_x* train_size)
    y_split = int(elements_y* train_size)
    x_train, x_test = x[:x_split], x[x_split:]
    y_train, y_test = y[:y_split], y[y_split:]
    
    return x_train, x_test, y_train, y_test

In [24]:
x_train, x_test, y_train, y_test = scratch_train_test_split(x,y, train_size=0.8)
print(x_train)
print(y_train)

[[-2.29374113e-01  1.90103034e+00]
 [ 2.70709974e+00  5.30195126e-01]
 [ 1.46837064e+00 -1.14147604e+00]
 [ 2.46463255e+00 -2.36692124e-01]
 [ 6.78049440e-01 -2.19208684e+00]
 [-1.26658152e+00  1.97258945e+00]
 [ 1.67483664e+00 -1.55932524e+00]
 [ 2.25701854e+00 -9.84595570e-01]
 [-9.07603154e-01  2.02453103e+00]
 [ 6.91658195e-01  2.83991926e+00]
 [-3.69047331e-03  2.72794750e+00]
 [ 1.64773650e+00 -1.37392022e+00]
 [ 4.22222154e-01 -2.24807641e+00]
 [ 1.76601743e+00 -5.17359929e-01]
 [ 3.64650383e-02  2.26861507e+00]
 [ 2.65071067e+00 -9.47349274e-01]
 [ 2.42340322e+00  4.86925716e-01]
 [ 2.45372019e+00 -1.16225960e-01]
 [-1.60770945e+00  1.29136745e+00]
 [-1.16513883e+00  1.40174924e+00]
 [ 1.19226877e-01  3.62537974e+00]
 [ 2.81410717e+00 -8.51160223e-01]
 [-2.05735708e+00  1.59371720e+00]
 [-1.10375132e+00  2.13604529e+00]
 [-1.00408384e+00  2.76905831e+00]
 [ 2.48267455e+00 -1.06055410e+00]
 [ 1.82068657e-03  4.23559938e+00]
 [ 3.40980745e-01 -4.07908535e+00]
 [-5.93349449e-01  1

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x = np.array([[0,0,0], [1,1,1], [2,2,2], [3,3,3], [4,4,4]])
y = np.array([0,1,2,3,4])

In [11]:
x.shape, y.shape
x, y

(array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]),
 array([0, 1, 2, 3, 4]))

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.8)
print(x_train)
print(y_train)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [0 0 0]]
[1 2 3 0]


In [29]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.8)
print(x_train)
print(y_train)

[[1 1 1]
 [4 4 4]
 [3 3 3]
 [2 2 2]]
[1 4 3 2]


In [30]:
print(x_test)
print(y_test)

[[0 0 0]]
[0]


PROBLEM 2

In [31]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [32]:
iris_dataset = load_iris()
columns_list = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
df = pd.DataFrame(iris_dataset['data'], columns=columns_list)
df['target'] = iris_dataset['target']
df = df[df['target'] !=0]
df

sepal_length  sepal_width  petal_length  petal_width  target
50            7.0          3.2           4.7          1.4       1
51            6.4          3.2           4.5          1.5       1
52            6.9          3.1           4.9          1.5       1
53            5.5          2.3           4.0          1.3       1
54            6.5          2.8           4.6          1.5       1
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[100 rows x 5 columns]

In [33]:
x1 = df.drop(['target'], axis=1)
y1 = df.target
x1.shape, y1.shape

((100, 4), (100,))

In [34]:
x1 = x1.to_numpy()
y1 = y1.to_numpy()

Simple Dataset 1

In [35]:
np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]
f0 = np.random.multivariate_normal(f0,cov,int(n_samples/2))
f1 = np.random.multivariate_normal(f1, cov, int(n_samples/2))
x = np.concatenate((f0,f1))
y = np.concatenate((np.ones((int(n_samples/2))), np.ones((int(n_samples/2))) *(-1))).astype(np.int)
random_index = np.random.permutation(np.arange(n_samples))
x2 = x[random_index]
y2 =y[random_index]
x2.shape, y2.shape

((500, 2), (500,))

In [68]:
iris_dataset = load_iris()
columns_list = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
df = pd.DataFrame(iris_dataset['data'], columns=columns_list)
df['target'] = iris_dataset['target']
df = df[df['target'] !=0]
df

sepal_length  sepal_width  petal_length  petal_width  target
50            7.0          3.2           4.7          1.4       1
51            6.4          3.2           4.5          1.5       1
52            6.9          3.1           4.9          1.5       1
53            5.5          2.3           4.0          1.3       1
54            6.5          2.8           4.6          1.5       1
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[100 rows x 5 columns]

In [69]:
np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]
f0 = np.random.multivariate_normal(f0,cov,int(n_samples/2))
f1 = np.random.multivariate_normal(f1, cov, int(n_samples/2))
x = np.concatenate((f0,f1))
y = np.concatenate((np.ones((int(n_samples/2))), np.ones((int(n_samples/2))) *(-1))).astype(np.int)
random_index = np.random.permutation(np.arange(n_samples))
x3 = x[random_index]
y3 =y[random_index]
x3.shape, y3.shape

((500, 2), (500,))

Simple Dataset 2

In [70]:
x3_train, x3_test, y3_train, y3_test = scratch_train_test_split(x3, y3, train_size=0.8)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x3_train)

x3_test = scaler.transform(x3_test)

Division of training data and verification data

In [72]:
x1_train, x1_test, y1_train, y1_test = scratch_train_test_split(x1, y1, train_size=0.8)

x2_train, x2_test, y2_train, y2_test = scratch_train_test_split(x2, y2, train_size=0.8)

x3_train, x3_test, y3_train, y3_test = train_test_split(x3, y3, train_size=0.8)

In [73]:
x3_train, x3_test, y3_train, y3_test = scratch_train_test_split(x3, y3, train_size=0.8)

Learning and estimation

SGD

Iris Dataset 1

In [76]:
from sklearn.linear_model import SGDClassifier
sgd1 = SGDClassifier(loss='log')
sgd1.fit(x1_train, y1_train)
y_preds1= sgd1.predict(x1_test)

In [77]:
y_preds1

array([2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2])

In [78]:
sgd1.score(x1_test, y1_test)

0.9

Dataset 2

In [79]:
sgd2 = SGDClassifier(loss='log')
sgd2.fit(x2_train, y2_train)
y_preds2= sgd2.predict(x2_test)

In [80]:
y_preds2

array([ 1, -1, -1, -1, -1, -1,  1,  1, -1,  1, -1,  1, -1,  1, -1, -1,  1,
       -1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1, -1, -1, -1,
        1, -1, -1,  1, -1,  1,  1,  1, -1,  1, -1, -1, -1,  1, -1, -1,  1,
       -1,  1, -1, -1, -1,  1,  1,  1, -1, -1,  1, -1, -1,  1,  1, -1,  1,
        1,  1,  1, -1, -1, -1, -1, -1,  1,  1, -1, -1,  1, -1,  1,  1,  1,
        1,  1, -1, -1, -1, -1,  1,  1,  1, -1,  1,  1, -1, -1,  1])

In [81]:
sgd2.score(x2_test, y2_test)

1.0

DATASET 3

In [82]:
sgd3 = SGDClassifier(loss='log')
sgd3.fit(x3_train, y3_train)
y_preds3= sgd3.predict(x3_test)

In [83]:
sgd3.score(x3_test, y3_test)

1.0

SVM

In [84]:
from sklearn.svm import SVC
svc1 = SVC()
svc1.fit(x1_train, y1_train)
y_preds4 = svc1.predict(x1_test)

In [85]:
svc1.score(x1_test, y1_test)

0.9

Dataset 2

In [86]:
svc2 = SVC()
svc2.fit(x2_train, y2_train)
y_preds4 = svc2.predict(x2_test)

In [87]:
svc2.score(x2_test, y2_test)

1.0

Dataset 3

In [90]:
svc3 = SVC()
svc3.fit(x3_train, y3_train)
y_preds4 = svc3.predict(x3_test)

In [91]:
svc3.score(x3_test, y3_test)

1.0

DECISION TREE

DATASET 1

In [92]:
from sklearn.tree import DecisionTreeClassifier
dt1 = DecisionTreeClassifier()
dt1.fit(x1_train, y1_train)
y_preds7 = dt1.predict(x1_test)

In [93]:
dt1.score(x1_test, y1_test)

0.9

Dataset 2

In [94]:
dt2 = DecisionTreeClassifier()
dt2.fit(x2_train, y2_train)
y_preds8 = dt2.predict(x2_test)

In [95]:
dt2.score(x2_test, y2_test)

1.0

Dataset 3

In [96]:
dt3 = DecisionTreeClassifier()
dt3.fit(x3_train, y3_train)
y_preds9 = dt3.predict(x3_test)

In [97]:
dt3.score(x3_test, y3_test)

1.0

PROBLEM 3

In [55]:
import pandas as pd
trains = pd.read_csv("C:\\Users\\SULCOTT\\Desktop\\assignment\\train.csv")
trains.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [56]:
x4 = trains.loc[:,['GrLivArea','YearBuilt']]
y4 = trains.loc[:,'SalePrice']

x4 = x4.to_numpy()
y4 = y4.to_numpy()
x4.shape, y4.shape

((1460, 2), (1460,))

In [57]:
x4_train, x4_test, y4_train, y4_test = scratch_train_test_split(x4, y4, train_size=0.8)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x4_train)

x4_test = scaler.transform(x4_test)

SGD

In [58]:
from sklearn.linear_model import SGDRegressor
reg1 = SGDRegressor()
reg1.fit(x4_train, y4_train)
y_preds10 = reg1.predict(x4_test)

In [59]:
reg1.score(x4_test, y4_test)

-19035591201900.02

In [60]:
from sklearn.metrics import mean_squared_error
mse1 = mean_squared_error(y4_test, y_preds10)
print("MSE SGD: {:,.3f}".format(mse1))

MSE SGD: 93,757,958,161,823,149,588,480.000


SVM

In [61]:
from sklearn.svm import SVR
reg2 = SVR()
reg2.fit(x4_train, y4_train)
y_preds11 = reg2.predict(x4_test)

In [62]:
reg2.score(x4_test, y4_test)

-0.0068091852995908475

In [63]:
mse2 = mean_squared_error(y4_test, y_preds11)
print("MSE SGD: {:,.3f}".format(mse2))

MSE SGD: 4,958,940,989.594


Decision tree

In [64]:
from sklearn.tree import DecisionTreeRegressor
reg3 = DecisionTreeRegressor()
reg3.fit(x4_train, y4_train)
y_preds12 = reg3.predict(x4_test)

In [65]:
reg3.score(x4_test, y4_test)

-2.488407366537478

In [66]:
mse3 = mean_squared_error(y4_test, y_preds12)
print("MSE SGD: {:,.3f}".format(mse3))

MSE SGD: 17,181,812,135.709
